// Code generated by "stringer -type state"; DO NOT EDIT.

package stack

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[normal-0]
	_ = x[betweenRoutine-1]
	_ = x[gotRoutineHeader-2]
	_ = x[gotFunc-3]
	_ = x[gotCreated-4]
	_ = x[gotFileFunc-5]
	_ = x[gotFileCreated-6]
	_ = x[gotUnavail-7]
	_ = x[gotRaceHeader1-8]
	_ = x[gotRaceHeader-9]
	_ = x[gotRaceOperationHeader-10]
	_ = x[gotRaceOperationFunc-11]
	_ = x[gotRaceOperationFile-12]
	_ = x[gotRaceGoroutineHeader-13]
	_ = x[gotRaceGoroutineFunc-14]
	_ = x[gotRaceGoroutineFile-15]
	_ = x[betweenRaces-16]
}

const _state_name = "normalbetweenRoutinegotRoutineHeadergotFuncgotCreatedgotFileFuncgotFileCreatedgotUnavailgotRaceHeader1gotRaceHeadergotRaceOperationHeadergotRaceOperationFuncgotRaceOperationFilegotRaceGoroutineHeadergotRaceGoroutineFuncgotRaceGoroutineFilebetweenRaces"

var _state_index = [...]uint8{0, 6, 20, 36, 43, 53, 64, 78, 88, 102, 115, 137, 157, 177, 199, 219, 239, 251}

func (i state) String() string {
	if i < 0 || i >= state(len(_state_index)-1) {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
